spring:
  cloud:
    stream:
      bindings:
        sample-stream-out-0:
          destination: sample-topic

  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
server:
  port: 8080